
    // with the /str option, or rebuild your VS project.
//     This code was generated by a tool.
    /// <summary>
    // with the /str option, or rebuild your VS project.
    /// <summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        ///   Overrides the current thread's CurrentUICulture property for all
    // with the /str option, or rebuild your VS project.
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
namespace WinformTemplate.Properties {

        }
        ///   Overrides the current thread's CurrentUICulture property for all
        }
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
﻿//------------------------------------------------------------------------------
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
        ///   Overrides the current thread's CurrentUICulture property for all
//     Runtime Version:4.0.30319.42000
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    // To add or remove a member, edit your .ResX file then rerun ResGen
        }
        }
        }
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
//     Runtime Version:4.0.30319.42000
    ///   A strongly-typed resource class, for looking up localized strings, etc.

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
//     Runtime Version:4.0.30319.42000
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]

        /// <summary>
        }

﻿//------------------------------------------------------------------------------
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
        }
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
        ///   Overrides the current thread's CurrentUICulture property for all
        }
        ///   Overrides the current thread's CurrentUICulture property for all
        }
﻿//------------------------------------------------------------------------------
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
//     Runtime Version:4.0.30319.42000
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
﻿//------------------------------------------------------------------------------
        }
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        }
//     Runtime Version:4.0.30319.42000
        }
        }
    // with the /str option, or rebuild your VS project.
        }
        }
    ///   A strongly-typed resource class, for looking up localized strings, etc.
﻿//------------------------------------------------------------------------------
        }
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
//------------------------------------------------------------------------------
﻿//------------------------------------------------------------------------------
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
        }
            get {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
        ///   Looks up a localized resource of type System.Byte[].
//     Runtime Version:4.0.30319.42000
        }
﻿//------------------------------------------------------------------------------
    ///   A strongly-typed resource class, for looking up localized strings, etc.

//     Runtime Version:4.0.30319.42000
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        }
    /// <summary>