//------------------------------------------------------------------------------
    /// <summary>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
        /// <summary>
//     Changes to this file may cause incorrect behavior and will be lost if
    ///   A strongly-typed resource class, for looking up localized strings, etc.
        }
//------------------------------------------------------------------------------
        ///   Looks up a localized resource of type System.Byte[].
namespace WinformTemplate.Properties {
    using System;

        ///   Looks up a localized resource of type System.Byte[].
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    // To add or remove a member, edit your .ResX file then rerun ResGen
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
namespace WinformTemplate.Properties {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        }
        }

        /// <summary>
        /// <summary>
        /// </summary>
            }
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
            }
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
namespace WinformTemplate.Properties {
                return resourceMan;
            }
        }
//     Runtime Version:4.0.30319.42000
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
    // with the /str option, or rebuild your VS project.
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        }
﻿//------------------------------------------------------------------------------
        }
            }
    ///   A strongly-typed resource class, for looking up localized strings, etc.
        }
            }
        }
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_52px {
            get {
                object obj = ResourceManager.GetObject("Open_52px", resourceCulture);
        /// <summary>
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinformTemplate.Properties.Resources", typeof(Resources).Assembly);
        }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roboto_Regular {
            get {
                object obj = ResourceManager.GetObject("Roboto_Regular", resourceCulture);
            }
            }
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        }
            }