//------------------------------------------------------------------------------
        }
//     the code is regenerated.
namespace WinformTemplate.Properties
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    }
//     the code is regenerated.
        public static Settings Default
        {
        }
namespace WinformTemplate.Properties
{
        }
        }
//     the code is regenerated.
//     This code was generated by a tool.
        }
namespace WinformTemplate.Properties
//     This code was generated by a tool.
        }
//     This code was generated by a tool.
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
        {
//     the code is regenerated.
//     This code was generated by a tool.
    }
            }
        }
    }
//     the code is regenerated.